### ISSUE TITLE
Rare Spawn Channel

### ISSUE THREAD

**Issue by rcbalugay24** [Astelan5/PokeHelper-Public#1]
Shinies isn't getting shown into the specified rare spawn channel

**Comment by Astelan5** [comment]
I am aware of this issue. It is not just shinies it seems random at least to me that it sometimes misses a rare spawn (Legendary or Shiny). If you can provide any additional details such as screen shots of the pokemeow messages before and after catching the pokemon when this happens that would be helpful for diagnosing the issue.

**Comment by rcbalugay24** [comment]
Would the old one work or it would be better if it's a present encounter?

**Comment by Astelan5** [comment]
If you failed to catch the Pokémon then yes it would work. Otherwise I will be pushing some diagnostic tools soon to try and figure out what is going on.

**Comment by rcbalugay24** [comment]
No, I meant for the screenshots. Which one would you like me to get?

**Comment by Astelan5** [comment]
Yes, I needed to see the message before you catch the pokemon. If you catch it the message changes to the one that shows your buddy gain xp. If you fail to catch it the message stays the same. Any screenshot that shows the original message where it failed to post the rare spawn.

**Comment by rcbalugay24** [comment]
Got it, I'll get you one as soon as I found a new one.
